Update deployment process
Despite what the Fly.io documentation says, you need to have a running
VM before running custom scripts. I hope that this change resolves the
issue that I encountered, listed below.

Error: app go-fly-example has no started VMs.
It may be unhealthy or not have been deployed yet.